// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfaw_fdSqBuWmQnYgGRKB8UqTVlOhL2es',
    appId: '1:1097834082720:web:555e14acd45391264b74c5',
    messagingSenderId: '1097834082720',
    projectId: 'flower-app-a54c1',
    authDomain: 'flower-app-a54c1.firebaseapp.com',
    storageBucket: 'flower-app-a54c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gH8PPs9TVbMmICmnaLEtMzPHwz9Z97g',
    appId: '1:1097834082720:android:8b8bc3660db623714b74c5',
    messagingSenderId: '1097834082720',
    projectId: 'flower-app-a54c1',
    storageBucket: 'flower-app-a54c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWtuOBPZRJq5ayBiG5qtBtLANUsxwXiOA',
    appId: '1:1097834082720:ios:97b798556f816eb84b74c5',
    messagingSenderId: '1097834082720',
    projectId: 'flower-app-a54c1',
    storageBucket: 'flower-app-a54c1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWtuOBPZRJq5ayBiG5qtBtLANUsxwXiOA',
    appId: '1:1097834082720:ios:205cd30da55655404b74c5',
    messagingSenderId: '1097834082720',
    projectId: 'flower-app-a54c1',
    storageBucket: 'flower-app-a54c1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
